#!/bin/bash
# https://docs.gitlab.com/runner/commands/#gitlab-runner-verify
# This command checks if the registered runners can connect to GitLab,
# but it doesn’t verify if the runners are being used by the
# GitLab Runner service.
#

# This operation cannot be undone. It updates the configuration file,
# so we make sure to have a backup of config.toml before executing it.
#

cp --force --backup=numbered /etc/gitlab-runner/config.toml /etc/gitlab-runner/

gitlab-runner verify --delete